const { pool } = require("../config/db");
const sharp = require("sharp");
const { decryptDocument } = require("./equipmentFinancePrivateDocumentsService");
const { renderCompletionPdf: renderBasePdf, renderCompletionWord: renderBaseWord } = require("./equipmentFinanceCompletionRendererService");

const PHOTO_DOCUMENT_TYPES = new Set(["installment_agreement","customer_agreement_copy","company_agreement_copy","boss_approval_pack","guarantor_undertaking","customer_statement","delivery_handover_note","arrears_notice","amendment_agreement","settlement_confirmation","ownership_transfer"]);
function placeholderPhoto(){return {placeholder:true,buffer:null,mimeType:null,dataUrl:"",documentId:null,documentNumber:"No customer photo supplied",checksum:null,fileName:""};}
function snapshotIdentity(document){const agreement=document.snapshot?.agreement||{};return {applicationId:Number(agreement.credit_application_id||agreement.application_id||document.snapshot?.document_context?.application_id||0)||null,customerId:Number(agreement.customer_id||0)||null};}
async function profilePhotoFallback(customerId){if(!customerId)return null;try{const [rows]=await pool.query("SELECT profile_photo_data_url FROM hire_customers WHERE id = ? AND profile_photo_data_url IS NOT NULL LIMIT 1",[customerId]);const dataUrl=String(rows[0]?.profile_photo_data_url||"");const match=/^data:image\/jpeg;base64,([A-Za-z0-9+/=]+)$/i.exec(dataUrl);if(!match)return null;const buffer=Buffer.from(match[1],"base64");return buffer.length?{placeholder:false,buffer,mimeType:"image/jpeg",dataUrl,documentId:null,documentNumber:"Customer profile photo",checksum:null,fileName:"customer-profile-photo.jpg"}:null;}catch(error){if(!["ER_NO_SUCH_TABLE","ER_BAD_FIELD_ERROR"].includes(error?.code))console.error("Customer profile photo fallback warning:",error);return null;}}
async function latestCustomerPhoto(document){if(!PHOTO_DOCUMENT_TYPES.has(document.document_type))return null;const {applicationId,customerId}=snapshotIdentity(document);if(!applicationId&&!customerId)return placeholderPhoto();try{const conditions=["document.document_type = 'customer_passport_photo'","document.document_status IN ('active','archived')"];const values=[];if(applicationId&&customerId){conditions.push("(document.application_id = ? OR document.customer_id = ?)");values.push(applicationId,customerId);}else if(applicationId){conditions.push("document.application_id = ?");values.push(applicationId);}else{conditions.push("document.customer_id = ?");values.push(customerId);}const [rows]=await pool.query(`SELECT document.* FROM equipment_finance_private_documents document WHERE ${conditions.join(" AND ")} ORDER BY CASE WHEN document.application_id = ? THEN 0 ELSE 1 END, CASE WHEN document.document_status = 'active' THEN 0 ELSE 1 END, document.version_number DESC, document.id DESC LIMIT 1`,[...values,applicationId||-1]);const row=rows[0];if(row){let buffer=decryptDocument(row);let mimeType=String(row.mime_type||"").toLowerCase();if(mimeType==="image/webp"){buffer=await sharp(buffer).png({compressionLevel:9}).toBuffer();mimeType="image/png";}if(["image/jpeg","image/png"].includes(mimeType))return {placeholder:false,buffer,mimeType,dataUrl:`data:${mimeType};base64,${buffer.toString("base64")}`,documentId:Number(row.id),documentNumber:row.document_number,checksum:row.content_checksum,fileName:row.original_file_name};}return (await profilePhotoFallback(customerId))||placeholderPhoto();}catch(error){if(error?.code!=="ER_NO_SUCH_TABLE"&&error?.code!=="ER_BAD_FIELD_ERROR")console.error("Customer photo document-render warning:",error);return (await profilePhotoFallback(customerId))||placeholderPhoto();}}
async function renderCompletionPdf(document,options={}){return renderBasePdf(document,options);}
async function renderCompletionWord(document){return renderBaseWord(document);}
module.exports={PHOTO_DOCUMENT_TYPES,latestCustomerPhoto,renderCompletionPdf,renderCompletionWord};
