const fs=require("node:fs");const path=require("node:path");const mysql=require("mysql2/promise");require("dotenv").config();
const MIGRATION_LOCK="chalin03:equipment-finance:opening-deposit-foundation-repair";
const MIGRATION_RECORD="20260805_equipment_finance_opening_deposit_foundation_repair";
const MIGRATION_FILE="20260805_equipment_finance_opening_deposit_foundation_repair.sql";
const VERIFIER_FILE="20260805_equipment_finance_opening_deposit_foundation_repair_verify.sql";
const INTEGRITY_MIGRATION_RECORD="20260803_equipment_finance_phase4_deposit_reservation_integrity";
const INTEGRITY_MIGRATION_FILE="20260803_equipment_finance_phase4_deposit_reservation_integrity.sql";
const REQUIRED_TRIGGERS=Object.freeze(["trg_equipment_finance_payment_gate_before_insert","trg_equipment_finance_reservation_gate_before_insert","trg_equipment_finance_commitment_gate_before_update"]);
function requiredEnv(a,b){const v=process.env[a]||process.env[b];if(!String(v||"").trim())throw new Error(`Missing required database variable ${a}${b?` or ${b}`:""}.`);return v}
function getSslConfig(e=process.env){if(String(e.DB_SSL||"").trim().toLowerCase()!=="true")return undefined;const ca=String(e.DB_SSL_CA_BASE64||"").trim();if(ca)return{ca:Buffer.from(ca,"base64").toString("utf8"),rejectUnauthorized:true};return{rejectUnauthorized:!["0","false","no","off"].includes(String(e.DB_SSL_REJECT_UNAUTHORIZED||"true").trim().toLowerCase())}}
function connectionOptions(){return{host:requiredEnv("DB_HOST","MYSQLHOST"),port:Number(process.env.DB_PORT||process.env.MYSQLPORT||3306),user:requiredEnv("DB_USER","MYSQLUSER"),password:requiredEnv("DB_PASSWORD","MYSQLPASSWORD"),database:requiredEnv("DB_NAME","MYSQLDATABASE"),ssl:getSslConfig(),connectTimeout:Number(process.env.DB_CONNECT_TIMEOUT_MS||15000),multipleStatements:false,timezone:"Z"}}
function hasExecutableSql(s){return String(s||"").replace(/\/\*[\s\S]*?\*\//g," ").split(/\r?\n/).map(x=>x.replace(/^\s*(?:--|#).*$/,"" )).join("\n").trim().length>0}
function splitSqlScript(s){const out=[];let d=";",b="";for(const line of String(s||"").replace(/\r\n/g,"\n").split("\n")){const m=line.match(/^\s*DELIMITER\s+(\S+)\s*$/i);if(m){if(hasExecutableSql(b))throw new Error("SQL DELIMITER appeared before the previous statement was complete.");b="";d=m[1];continue}b+=`${line}\n`;const t=b.trimEnd();if(!t.endsWith(d))continue;const st=t.slice(0,-d.length).trim();if(st)out.push(st);b=""}if(hasExecutableSql(b))throw new Error("SQL script ended with an incomplete statement.");return out}
function migrationDirectory(){const c=[path.resolve(__dirname,"../database/migrations"),path.resolve(__dirname,"../../database/migrations")];const e=c.find(x=>fs.existsSync(x));if(!e)throw new Error(`Approved Opening Deposit migration directory is missing. Checked: ${c.join(", ")}`);return e}
function readMigrationFile(f){const p=path.join(migrationDirectory(),f);if(!fs.existsSync(p))throw new Error(`Approved Opening Deposit SQL file is missing: ${p}`);return fs.readFileSync(p,"utf8")}
async function verifyDatabaseIdentity(c){const [[r]]=await c.query("SELECT DATABASE() AS database_name");const db=String(r?.database_name||"").trim(),expected=String(process.env.CHALIN03_EXPECTED_DATABASE||"").trim();if(!db||!expected)throw new Error("Set CHALIN03_EXPECTED_DATABASE to the exact Railway production database name.");if(db!==expected)throw new Error(`Connected database ${db} does not match CHALIN03_EXPECTED_DATABASE.`);return db}
async function executeStatements(c,ss,label){const out=[];for(let i=0;i<ss.length;i++){try{const[r]=await c.query(ss[i]);out.push(Array.isArray(r)?r:[])}catch(e){e.message=`${label} failed at statement ${i+1} of ${ss.length}: ${e.message}`;throw e}}return out}
function count(results,index,field){return Number(results[index]?.[0]?.[field]||0)}
function validateRepair(r){if(r.length!==12)throw new Error(`Opening Deposit repair verifier returned ${r.length} result sets instead of 12.`);const checks=[[0,"missing_deposit_reservation_columns"],[1,"missing_deposit_reservation_indexes"],[2,"missing_deposit_reservation_foreign_keys"],[3,"missing_deposit_reservation_triggers"],[4,"bypassed_controlled_finance_payments"],[5,"invalid_opening_deposit_payments"],[6,"invalid_controlled_deposit_balances"],[7,"invalid_reserved_finance_agreements"],[8,"invalid_controlled_finance_sale_locks"],[9,"reserved_finance_assets_active_on_hire"],[10,"forbidden_deposit_hire_link_columns"],[11,"deposit_reservation_migration_record_missing"]];for(const[i,f]of checks)if(count(r,i,f)!==0)throw new Error(`Opening Deposit verifier failed: ${f}.`)}
async function validateIntegrityTriggers(c){const p=REQUIRED_TRIGGERS.map(()=>"?").join(","), [rows]=await c.query(`SELECT TRIGGER_NAME,EVENT_MANIPULATION,ACTION_TIMING FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME IN (${p})`,REQUIRED_TRIGGERS);const found=new Map(rows.map(x=>[x.TRIGGER_NAME,x]));const missing=REQUIRED_TRIGGERS.filter(x=>!found.has(x));if(missing.length)throw new Error(`Opening Deposit integrity triggers are still missing: ${missing.join(", ")}.`);const expected=new Map([[REQUIRED_TRIGGERS[0],["INSERT","BEFORE"]],[REQUIRED_TRIGGERS[1],["INSERT","BEFORE"]],[REQUIRED_TRIGGERS[2],["UPDATE","BEFORE"]]]);for(const[n,[ev,t]]of expected){const row=found.get(n);if(row.EVENT_MANIPULATION!==ev||row.ACTION_TIMING!==t)throw new Error(`Opening Deposit integrity trigger ${n} has invalid timing.`)}}
async function runEquipmentFinanceOpeningDepositFoundationRepair(){const c=await mysql.createConnection(connectionOptions());let locked=false;try{const db=await verifyDatabaseIdentity(c);const[[lr]]=await c.query("SELECT GET_LOCK(?,30) AS acquired",[MIGRATION_LOCK]);locked=Number(lr?.acquired||0)===1;if(!locked)throw new Error("Could not acquire the Opening Deposit foundation repair lock.");await executeStatements(c,splitSqlScript(readMigrationFile(MIGRATION_FILE)),"Equipment Finance Opening Deposit foundation repair");const vr=await executeStatements(c,splitSqlScript(readMigrationFile(VERIFIER_FILE)),"Equipment Finance Opening Deposit foundation verifier");validateRepair(vr);await executeStatements(c,splitSqlScript(readMigrationFile(INTEGRITY_MIGRATION_FILE)),"Equipment Finance Opening Deposit integrity trigger repair");await validateIntegrityTriggers(c);console.log(`Verified ${MIGRATION_RECORD} and ${INTEGRITY_MIGRATION_RECORD} on ${db}.`);return{applied:true,database_name:db,migration:MIGRATION_RECORD,integrity_migration:INTEGRITY_MIGRATION_RECORD}}finally{if(locked){try{await c.query("SELECT RELEASE_LOCK(?)",[MIGRATION_LOCK])}catch{}}await c.end()}}
if(require.main===module)runEquipmentFinanceOpeningDepositFoundationRepair().catch(e=>{console.error("Equipment Finance Opening Deposit startup repair failed.");console.error(e.message);process.exit(1)});
module.exports={INTEGRITY_MIGRATION_FILE,INTEGRITY_MIGRATION_RECORD,MIGRATION_FILE,MIGRATION_LOCK,MIGRATION_RECORD,REQUIRED_TRIGGERS,VERIFIER_FILE,executeStatements,hasExecutableSql,runEquipmentFinanceOpeningDepositFoundationRepair,splitSqlScript,validateIntegrityTriggers,validateRepair,verifyDatabaseIdentity};
