const fs=require("node:fs");const path=require("node:path");const mysql=require("mysql2/promise");require("dotenv").config();
const MIGRATION_LOCK="chalin03:equipment-finance:opening-deposit-foundation-repair";const MIGRATION_RECORD="20260805_equipment_finance_opening_deposit_foundation_repair";const MIGRATION_FILE="20260805_equipment_finance_opening_deposit_foundation_repair.sql";const VERIFIER_FILE="20260805_equipment_finance_opening_deposit_foundation_repair_verify.sql";const INTEGRITY_MIGRATION_RECORD="20260803_equipment_finance_phase4_deposit_reservation_integrity";const INTEGRITY_MIGRATION_FILE="20260803_equipment_finance_phase4_deposit_reservation_integrity.sql";const REQUIRED_TRIGGERS=["trg_equipment_finance_payment_gate_before_insert","trg_equipment_finance_reservation_gate_before_insert","trg_equipment_finance_commitment_gate_before_update"];
function req(a,b){const v=process.env[a]||process.env[b];if(!String(v||"").trim())throw Error(`Missing required database variable ${a}${b?` or ${b}`:""}.`);return v}function ssl(){if(String(process.env.DB_SSL||"").trim().toLowerCase()!=="true")return undefined;const ca=String(process.env.DB_SSL_CA_BASE64||"").trim();return ca?{ca:Buffer.from(ca,"base64").toString("utf8"),rejectUnauthorized:true}:{rejectUnauthorized:!["0","false","no","off"].includes(String(process.env.DB_SSL_REJECT_UNAUTHORIZED||"true").trim().toLowerCase())}}function opts(){return{host:req("DB_HOST","MYSQLHOST"),port:Number(process.env.DB_PORT||process.env.MYSQLPORT||3306),user:req("DB_USER","MYSQLUSER"),password:req("DB_PASSWORD","MYSQLPASSWORD"),database:req("DB_NAME","MYSQLDATABASE"),ssl:ssl(),connectTimeout:Number(process.env.DB_CONNECT_TIMEOUT_MS||15000),multipleStatements:false,timezone:"Z"}}
function split(s){const out=[];let d=";",b="";for(const line of String(s||"").replace(/\r\n/g,"\n").split("\n")){const m=line.match(/^\s*DELIMITER\s+(\S+)\s*$/i);if(m){if(b.trim())throw Error("SQL DELIMITER appeared before previous statement was complete.");b="";d=m[1];continue}b+=line+"\n";const t=b.trimEnd();if(!t.endsWith(d))continue;const st=t.slice(0,-d.length).trim();if(st)out.push(st);b=""}if(b.trim())throw Error("SQL script ended with an incomplete statement.");return out}
function dir(){const c=[path.resolve(__dirname,"../database/migrations"),path.resolve(__dirname,"../../database/migrations")],e=c.find(fs.existsSync);if(!e)throw Error(`Approved Opening Deposit migration directory is missing. Checked: ${c.join(", ")}`);return e}function sql(f){const p=path.join(dir(),f);if(!fs.existsSync(p))throw Error(`Approved Opening Deposit SQL file is missing: ${p}`);return fs.readFileSync(p,"utf8")}
async function exec(c,ss,label){const r=[];for(let i=0;i<ss.length;i++){try{const[x]=await c.query(ss[i]);r.push(Array.isArray(x)?x:[])}catch(e){e.message=`${label} failed at statement ${i+1} of ${ss.length}: ${e.message}`;throw e}}return r}
async function identity(c){const[[r]]=await c.query("SELECT DATABASE() AS database_name");const db=String(r?.database_name||"").trim(),ex=String(process.env.CHALIN03_EXPECTED_DATABASE||"").trim();if(!db||!ex||db!==ex)throw Error("Opening Deposit production database identity check failed.");return db}
function validate(r){if(r.length!==12)throw Error(`Opening Deposit repair verifier returned ${r.length} result sets instead of 12.`);for(const[i,f]of [[0,"missing_deposit_reservation_columns"],[1,"missing_deposit_reservation_indexes"],[2,"missing_deposit_reservation_foreign_keys"],[3,"missing_deposit_reservation_triggers"]])if(Number(r[i]?.[0]?.[f]||0)!==0)throw Error(`Opening Deposit verifier failed: ${f}.`)}
async function triggers(c){const p=REQUIRED_TRIGGERS.map(()=>"?").join(","),[rows]=await c.query(`SELECT TRIGGER_NAME,EVENT_MANIPULATION,ACTION_TIMING FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME IN (${p})`,REQUIRED_TRIGGERS);const m=REQUIRED_TRIGGERS.filter(n=>!rows.some(r=>r.TRIGGER_NAME===n));if(m.length)throw Error(`Opening Deposit integrity triggers are still missing: ${m.join(", ")}.`);const want=[["INSERT","BEFORE"],["INSERT","BEFORE"],["UPDATE","BEFORE"]];for(let i=0;i<REQUIRED_TRIGGERS.length;i++){const r=rows.find(x=>x.TRIGGER_NAME===REQUIRED_TRIGGERS[i]);if(r.EVENT_MANIPULATION!==want[i][0]||r.ACTION_TIMING!==want[i][1])throw Error(`Opening Deposit integrity trigger ${REQUIRED_TRIGGERS[i]} has invalid timing.`)}}
async function runEquipmentFinanceOpeningDepositFoundationRepair(){const c=await mysql.createConnection(opts());let locked=false;try{const db=await identity(c);const[[lr]]=await c.query("SELECT GET_LOCK(?,30) AS acquired",[MIGRATION_LOCK]);locked=Number(lr?.acquired||0)===1;if(!locked)throw Error("Could not acquire the Opening Deposit foundation repair lock.");await exec(c,split(sql(MIGRATION_FILE)),"Opening Deposit foundation repair");validate(await exec(c,split(sql(VERIFIER_FILE)),"Opening Deposit foundation verifier"));await exec(c,split(sql(INTEGRITY_MIGRATION_FILE)),"Opening Deposit integrity trigger repair");await triggers(c);console.log(`Verified ${MIGRATION_RECORD} and ${INTEGRITY_MIGRATION_RECORD} on ${db}.`);return{applied:true,database_name:db,migration:MIGRATION_RECORD,integrity_migration:INTEGRITY_MIGRATION_RECORD}}finally{if(locked){try{await c.query("SELECT RELEASE_LOCK(?)",[MIGRATION_LOCK])}catch{}}await c.end()}}
if(require.main===module)runEquipmentFinanceOpeningDepositFoundationRepair().catch(e=>{console.error("Equipment Finance Opening Deposit startup repair failed.");console.error(e.message);process.exit(1)});module.exports={MIGRATION_FILE,MIGRATION_LOCK,MIGRATION_RECORD,VERIFIER_FILE,INTEGRITY_MIGRATION_FILE,INTEGRITY_MIGRATION_RECORD,REQUIRED_TRIGGERS,runEquipmentFinanceOpeningDepositFoundationRepair,validate,triggers};
