const test = require("node:test");
const assert = require("node:assert/strict");

const {
  MINIMUMS,
  applyRuntimeCostControl,
} = require("../services/runtimeCostControlBootstrap");

test("runtime cost controls do not apply outside production", () => {
  const env = {
    NODE_ENV: "test",
    EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS: "1000",
    EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS: "1000",
    NOTIFICATION_SYNC_INTERVAL_MINUTES: "1",
    SMS_DELIVERY_POLL_INTERVAL_MS: "1000",
    DEBT_REMINDER_INTERVAL_MINUTES: "1",
    EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS: "1000",
    INSTALLMENT_REMINDER_INTERVAL_MINUTES: "1",
    EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES: "1",
  };

  const result = applyRuntimeCostControl(env);

  assert.equal(result.applied, false);
  assert.equal(env.EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS, "1000");
  assert.equal(env.EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS, "1000");
  assert.equal(env.NOTIFICATION_SYNC_INTERVAL_MINUTES, "1");
  assert.equal(env.SMS_DELIVERY_POLL_INTERVAL_MS, "1000");
  assert.equal(env.DEBT_REMINDER_INTERVAL_MINUTES, "1");
  assert.equal(env.EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS, "1000");
  assert.equal(env.INSTALLMENT_REMINDER_INTERVAL_MINUTES, "1");
  assert.equal(env.EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES, "1");
});

test("production scheduler intervals are clamped to aggressive cost minimums", () => {
  const env = {
    NODE_ENV: "production",
    EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS: "1000",
    EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS: "1000",
    NOTIFICATION_SYNC_INTERVAL_MINUTES: "5",
    SMS_DELIVERY_POLL_INTERVAL_MS: "1000",
    DEBT_REMINDER_INTERVAL_MINUTES: "1",
    EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS: "1000",
    INSTALLMENT_REMINDER_INTERVAL_MINUTES: "1",
    EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES: "1",
  };

  const result = applyRuntimeCostControl(env);

  assert.equal(result.applied, true);
  assert.equal(Number(env.EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS), MINIMUMS.EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS);
  assert.equal(Number(env.EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS), MINIMUMS.EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS);
  assert.equal(Number(env.NOTIFICATION_SYNC_INTERVAL_MINUTES), MINIMUMS.NOTIFICATION_SYNC_INTERVAL_MINUTES);
  assert.equal(Number(env.SMS_DELIVERY_POLL_INTERVAL_MS), MINIMUMS.SMS_DELIVERY_POLL_INTERVAL_MS);
  assert.equal(Number(env.DEBT_REMINDER_INTERVAL_MINUTES), MINIMUMS.DEBT_REMINDER_INTERVAL_MINUTES);
  assert.equal(Number(env.EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS), MINIMUMS.EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS);
  assert.equal(Number(env.INSTALLMENT_REMINDER_INTERVAL_MINUTES), MINIMUMS.INSTALLMENT_REMINDER_INTERVAL_MINUTES);
  assert.equal(Number(env.EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES), MINIMUMS.EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES);
});

test("production scheduler intervals preserve deliberately slower settings", () => {
  const env = {
    NODE_ENV: "production",
    EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS: "14400000",
    EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS: "3600000",
    NOTIFICATION_SYNC_INTERVAL_MINUTES: "720",
    SMS_DELIVERY_POLL_INTERVAL_MS: "1800000",
    DEBT_REMINDER_INTERVAL_MINUTES: "720",
    EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS: "21600000",
    INSTALLMENT_REMINDER_INTERVAL_MINUTES: "720",
    EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES: "720",
  };

  applyRuntimeCostControl(env);

  assert.equal(env.EQUIPMENT_FINANCE_BOSS_ALERT_POLL_MS, "14400000");
  assert.equal(env.EQUIPMENT_FINANCE_PAYMENT_MESSAGE_INTERVAL_MS, "3600000");
  assert.equal(env.NOTIFICATION_SYNC_INTERVAL_MINUTES, "720");
  assert.equal(env.SMS_DELIVERY_POLL_INTERVAL_MS, "1800000");
  assert.equal(env.DEBT_REMINDER_INTERVAL_MINUTES, "720");
  assert.equal(env.EQUIPMENT_FINANCE_REMINDER_INTERVAL_MS, "21600000");
  assert.equal(env.INSTALLMENT_REMINDER_INTERVAL_MINUTES, "720");
  assert.equal(env.EQUIPMENT_SALES_REMINDER_INTERVAL_MINUTES, "720");
});
