import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const read = (relativePath) =>
  fs.readFileSync(path.join(root, relativePath), "utf8");

const loginEntry = read("src/pages/LoginPage.jsx");
const bankLayer = read("src/pages/LoginPageBank.jsx");
const loginEngine = read("src/pages/LoginPageV4.jsx");
const bankStyles = read("src/styles/commandGateBankPolish.css");
const mobileStyles = read("src/styles/mobileExperience.css");
const mobileNavigation = read("src/components/CompactSidebarNavigation.jsx");
const historyTracker = read("src/utils/commandGateHistoryTracker.js");
const serviceWorker = read("public/sw.js");
const security = read("src/pages/ChangePasswordPage.jsx");
const main = read("src/main.jsx");
const arrival = read("src/components/CommandArrivalBanner.jsx");
const passkeyRoutes = read("../backend/routes/passkeyRoutes.js");
const server = read("../backend/server.js");
const authRoutes = read("../backend/routes/authRoutes.js");
const migration = read("../database/migrations/20260722_command_gate_passkeys.sql");

assert.match(loginEntry, /LoginPageBank/);
assert.match(bankLayer, /LoginPageV4/);
assert.match(bankLayer, /biometricState/);
assert.match(bankLayer, /Verify to continue/);
assert.match(bankLayer, /Identity verified/);
assert.match(bankLayer, /Waiting for device verification/);
assert.match(bankLayer, /Secure verification complete/);
assert.match(bankLayer, /\.gate4__passkey/);
assert.match(bankLayer, /\/chalin03-logo\.png/);
assert.match(loginEngine, /authenticateWithPasskey/);
assert.match(loginEngine, /registerPasskey/);
assert.match(loginEngine, /automaticDeviceSetup/);
assert.match(loginEngine, /isLoggedIn && !postLoginProcessing/);
assert.match(loginEngine, /request-otp/);
assert.match(loginEngine, /getPostLoginDestination/);
assert.match(loginEngine, /Emergency Operations/);
assert.match(loginEngine, /window\.setTimeout\(resolve, 360\)/);
assert.match(loginEngine, /window\.setTimeout\(resolve, 850\)/);
assert.match(bankStyles, /Sign in with face or fingerprint/);
assert.match(bankStyles, /Fresh face, fingerprint or device-PIN verification is required/);
assert.match(bankStyles, /\/chalin03-logo\.png/);
assert.match(bankStyles, /\.gate4__version[\s\S]*display:\s*none/);
assert.match(bankStyles, /\.gate4__logo span[\s\S]*display:\s*none/);
assert.match(bankStyles, /@media \(max-width: 640px\)/);
assert.match(mobileStyles, /Dedicated mobile operating layer/);
assert.match(mobileStyles, /\.compact-sidebar-navigation\.is-mobile-navigation/);
assert.match(mobileStyles, /grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/);
assert.match(mobileStyles, /\.chalin-route-dashboard/);
assert.match(mobileStyles, /\.chalin-route-new-sale/);
assert.match(mobileStyles, /\.chalin-route-products/);
assert.match(mobileStyles, /body\.chalin-route-login/);
assert.match(mobileNavigation, /isMobileNavigation/);
assert.match(mobileNavigation, /new Set\(\[title\]\)/);
assert.match(historyTracker, /chalin-route-/);
assert.match(historyTracker, /chalin:route-change/);
assert.match(serviceWorker, /mobile-experience/);
assert.match(security, /registerPasskey/);
assert.match(security, /auth\/passkeys/);
assert.match(security, /Temporary station mode/);
assert.match(main, /EmergencyCommandOverlay/);
assert.match(main, /CommandArrivalBanner/);
assert.match(main, /installCommandGateHistoryTracker/);
assert.match(main, /mobileExperience\.css/);
assert.match(arrival, /Welcome back/);
assert.match(passkeyRoutes, /userVerification:\s*"required"/);
assert.match(passkeyRoutes, /requireUserVerification:\s*true/);
assert.match(passkeyRoutes, /expectedUserHandle/);
assert.match(server, /\/api\/auth\/passkeys/);
assert.match(authRoutes, /router\.commandGateAuth\s*=\s*Object\.freeze/);
assert.match(migration, /ADDITIVE MIGRATION ONLY/);
assert.match(migration, /BACKUP REQUIRED/);
assert.match(migration, /schema_migrations/);

console.log("Bank login and dedicated mobile experience contracts passed.");
